from pydantic import BaseModel


class SecurityReport(BaseModel):
    """
    Final report generated by Guardian AI.
    """

    overall_risk: str

    confidence: float

    findings: list[str]

    recommendations: list[str]